### ISSUE TITLE
invalid db init

### ISSUE THREAD

**Issue by vitaly-t** [snirad/times#1]
```js
const db = new pgp(pgUrl);
```
should be just:
```js
const db = pgp(pgUrl);
```
as per the [Getting Started](https://github.com/vitaly-t/pg-promise#getting-started) ;)

**Comment by snirad** [comment]
Thanks :) !,

I thought I fixed that !!

**Comment by snirad** [comment]
by the way, how did you find this O_o

**Comment by vitaly-t** [comment]
GitHub shows new entries for the library.
